# Generated by Django 4.2.27 on 2026-01-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_organizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='AuraLink', max_length=100)),
                ('hero_headline', models.CharField(blank=True, default='Plan, Manage, & Join Events Easily', max_length=255)),
                ('hero_subtext', models.TextField(blank=True, default='Discover curated events near you and manage your own with ease.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
            ],
        ),
    ]
